#spring.application.name=product-catalog-service

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/product_catalog
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/product_catalog
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_catalog}
#spring.datasource.username=postgres
#spring.datasource.password=25scse2140006

# PostgreSQL Database Configuration
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_catalog}
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD:25scse2140006}

# JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
## Actuator
#management.endpoints.web.exposure.include=health
#management.endpoint.health.show-details=always
#
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#spring.jpa.show-sql=false

spring.application.name=product-catalog-service

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/product_catalog}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:25scse2140006}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always