{
 "title": "Product Catalog Service Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "JVM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"product-catalog-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=\"product-catalog-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"product-catalog-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"product-catalog-service\",area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"product-catalog-service\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "up{job=\"product-catalog-service\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}