apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-catalog-service

  labels:
    app: product-catalog-service
    app.kubernetes.io/name: product-catalog-service
    app.kubernetes.io/managed-by: Helm

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: product-catalog-service

  template:
    metadata:
      labels:
        app: product-catalog-service
        app.kubernetes.io/name: product-catalog-service

    spec:
      containers:

        - name: product-catalog-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP

          env:

            - name: DB_URL
              value: {{ .Values.database.url | quote }}

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.usernameKey }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.passwordKey }}

          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}

            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}

            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}